// 🎨 Словарь цветов
const colorNames = {
    '#1a1a2e': 'Тёмно-синий', '#4a5d4e': 'Зелёный', '#7a3a4a': 'Бордовый',
    '#808080': 'Серый', '#d4a574': 'Бежевый', '#f5f5dc': 'Кремовый',
    '#374151': 'Графитовый', '#6b7280': 'Серебристый', '#8b4513': 'Коричневый',
    '#ffffff': 'Белый', '#87ceeb': 'Голубой', '#d2b48c': 'Песочный',
    '#4169e1': 'Синий', '#2f4f4f': 'Тёмно-зелёный', '#ffb6c1': 'Розовый',
    '#800020': 'Винный', '#964b00': 'Охра', '#1a1a1a': 'Чёрный',
    '#2a2a2a': 'Тёмно-серый', '#3a3a3a': 'Угольный'
};

function getColorName(hex) {
    if (!hex) return 'Не указан';
    const normalized = hex.trim().toLowerCase();
    return colorNames[normalized] || colorNames[hex] || 'Другой оттенок';
}

// 📦 Данные товаров (32 товара)
const products = [
    { id: 1, name: "Шёлковое платье миди", brand: "VELORE", category: "women", price: 12990, oldPrice: 18990, badge: "sale", badgeText: "-32%", desc: "Элегантное платье из натурального шёлка с мягким драпированием.", colors: ["#1a1a2e", "#4a5d4e", "#7a3a4a"], sizes: ["XS", "S", "M", "L", "XL"], reviews: [{name: "Анастасия", stars: 5, text: "Невероятное качество!"}], image: "https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotLez2mZ8U_RnqKUbcyoMLRDSuDKFIpkWbeZvD27Zw7Tw", images: ["https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotLez2mZ8U_RnqKUbcyoMLRDSuDKFIpkWbeZvD27Zw7Tw", "https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2Noti15Z4EAkt0-_Rm3yr6EOn2UQGk9StaSO2uPk4tWwj40", "https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2Not5yMu9L5Ls-4Lv4eLHQFF3WUQGk9StaSO2uPk4tWwj40"] },
    { id: 2, name: "Кашемировый свитер", brand: "LUXE KNIT", category: "women", price: 8990, oldPrice: null, badge: "new", badgeText: "New", desc: "Мягкий свитер из 100% кашемира.", colors: ["#808080", "#d4a574","#f5f5dc"], sizes: ["S", "M", "L"], reviews: [{name: "Мария", stars: 5, text: "Самый мягкий свитер!"}], image: "https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotQYNGCnOY1heZ3kMySTl-8zSuDKFIpkWbeZvD27Zw7Tw", images: ["https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotQYNGCnOY1heZ3kMySTl-8zSuDKFIpkWbeZvD27Zw7Tw"] },
    { id: 3, name: "Классический блейзер", brand: "FORMAL CO", category: "men", price: 15990, oldPrice: null, badge: "hot", badgeText: "Хит", desc: "Приталенный блейзер из итальянской шерсти.", colors: ["#1a1a2e", "#374151", "#6b7280"], sizes: ["46", "48", "50", "52", "54"], reviews: [{name: "Дмитрий", stars: 5, text: "Отличный блейзер!"}], image: "https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotdeTq8p2KNJ83PFmpbOfY-DSuDKFIpkWbeZvD27Zw7Tw", images: ["https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotdeTq8p2KNJ83PFmpbOfY-DSuDKFIpkWbeZvD27Zw7Tw"] },
    { id: 4, name: "Кожаная сумка-тоут", brand: "VELORE", category: "accessories", price: 9490, oldPrice: 13990, badge: "sale", badgeText: "-32%", desc: "Вместительная сумка из натуральной кожи.", colors: ["#8B4513", "#1a1a2e", "#4a5d4e"], sizes: ["One Size"], reviews: [{name: "Ольга", stars: 5, text: "Очень вместительная!"}], image: "https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotN5WCC9Mi4pSpEw-7GxRxiTSuDKFIpkWbeZvD27Zw7Tw", images: ["https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotN5WCC9Mi4pSpEw-7GxRxiTSuDKFIpkWbeZvD27Zw7Tw"] },
    { id: 5, name: "Кроссовки Premium", brand: "STRIDE", category: "shoes", price: 11990, oldPrice: null, badge: "new", badgeText: "New", desc: "Стильные кроссовки из премиальной кожи.", colors: ["#ffffff", "#1a1a2e", "#7a3a4a"], sizes: ["38", "39", "40", "41", "42", "43", "44"], reviews: [{name: "Иван", stars: 5, text: "Удобные и стильные!"}], image: "https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2Notl718PzKHucmNgpZHi6k0mTSuDKFIpkWbeZvD27Zw7Tw", images: ["https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2Notl718PzKHucmNgpZHi6k0mTSuDKFIpkWbeZvD27Zw7Tw"] },
    { id: 6, name: "Льняные брюки", brand: "SUMMER LINE", category: "men", price: 6990, oldPrice: 9990, badge: "sale", badgeText: "-30%", desc: "Лёгкие брюки из натурального льна.", colors: ["#f5f5dc", "#87CEEB", "#D2B48C"], sizes: ["44", "46", "48", "50", "52"], reviews: [{name: "Сергей", stars: 4, text: "Лёгкие и удобные."}], image: "https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotKQLtO4WY5dOKLuSlhewG1DSuDKFIpkWbeZvD27Zw7Tw", images: ["https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotLphvLf2zE7MyiPuezH2CX2UQGk9StaSO2uPk4tWwj40"] },
    { id: 7, name: "Солнцезащитные очки", brand: "VISTA", category: "accessories", price: 4990, oldPrice: null, badge: "hot", badgeText: "Хит", desc: "Поляризованные линзы UV400 в стильной оправе.", colors: ["#1a1a2e", "#8B4513", "#4a5d4e"], sizes: ["One Size"], reviews: [{name: "Анна", stars: 5, text: "Отличные очки!"}], image: "https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2Not9ikvpy8eLbIbG3nbpaE03jSuDKFIpkWbeZvD27Zw7Tw", images: ["https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2Not9ikvpy8eLbIbG3nbpaE03jSuDKFIpkWbeZvD27Zw7Tw"] },
    { id: 8, name: "Пальто оверсайз", brand: "VELORE", category: "women", price: 19990, oldPrice: null, badge: "new", badgeText: "New", desc: "Тёплое пальто из смесовой шерсти.", colors: ["#D2B48C", "#1a1a2e", "#808080"], sizes: ["S", "M", "L", "XL"], reviews: [{name: "Полина", stars: 5, text: "Роскошное пальто!"}], image: "https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotVOsOjueRcsgJu_jjfaSpJDSuDKFIpkWbeZvD27Zw7Tw", images: ["https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotVOsOjueRcsgJu_jjfaSpJDSuDKFIpkWbeZvD27Zw7Tw"] },
    { id: 9, name: "Джинсы Slim Fit", brand: "DENIM LAB", category: "men", price: 7490, oldPrice: 10990, badge: "sale", badgeText: "-32%", desc: "Классические джинсы slim fit из плотного денима.", colors: ["#1a1a2e", "#4169E1", "#2F4F4F"], sizes: ["29", "30", "31", "32", "33", "34"], reviews: [{name: "Максим", stars: 4, text: "Хорошие джинсы."}], image: "https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotzABzjlrqOFR4zIh4OrJINjSuDKFIpkWbeZvD27Zw7Tw", images: ["https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotzABzjlrqOFR4zIh4OrJINjSuDKFIpkWbeZvD27Zw7Tw"] },
    { id: 10, name: "Блузка с бантом", brand: "FEMME", category: "women", price: 5990, oldPrice: null, badge: "new", badgeText: "New", desc: "Изящная блузка с декоративным бантом.", colors: ["#ffffff", "#FFB6C1", "#1a1a2e"], sizes: ["XS", "S", "M", "L"], reviews: [{name: "Дарья", stars: 5, text: "Очень нежная!"}], image: "https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotXUgWUaxik2Q9yORqhWu-eTSuDKFIpkWbeZvD27Zw7Tw", images: ["https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotXUgWUaxik2Q9yORqhWu-eTSuDKFIpkWbeZvD27Zw7Tw"] },
    { id: 11, name: "Кожаные ботинки", brand: "STRIDE", category: "shoes", price: 14990, oldPrice: 19990, badge: "sale", badgeText: "-25%", desc: "Классические кожаные ботинки ручной работы.", colors: ["#8B4513", "#1a1a2e"], sizes: ["40", "41", "42", "43", "44", "45"], reviews: [{name: "Роман", stars: 5, text: "Качественная кожа!"}], image: "https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2Not0vpZyZNtTTnF971YEnZN0jSuDKFIpkWbeZvD27Zw7Tw", images: ["https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2Not0vpZyZNtTTnF971YEnZN0jSuDKFIpkWbeZvD27Zw7Tw"] },
    { id: 12, name: "Шарф из кашемира", brand: "VELORE", category: "accessories", price: 3990, oldPrice: null, badge: "hot", badgeText: "Хит", desc: "Мягкий кашемировый шарф в клетку.", colors: ["#808080", "#4a5d4e", "#7a3a4a"], sizes: ["One Size"], reviews: [{name: "Елена", stars: 5, text: "Невероятно мягкий!"}], image: "https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotdIWYXs5x4hkF6ozSW5cV2WUQGk9StaSO2uPk4tWwj40", images: ["https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotdIWYXs5x4hkF6ozSW5cV2WUQGk9StaSO2uPk4tWwj40"] },
    { id: 13, name: "Юбка-карандаш", brand: "FEMME", category: "women", price: 4990, oldPrice: 6990, badge: "sale", badgeText: "-29%", desc: "Классическая юбка из плотной ткани.", colors: ["#1a1a2e", "#800020", "#374151"], sizes: ["XS", "S", "M", "L"], reviews: [{name: "Татьяна", stars: 5, text: "Отлично сидит."}], image: "https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotI0E4iskiA6qMkUs7wen4ADSuDKFIpkWbeZvD27Zw7Tw", images: ["https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotI0E4iskiA6qMkUs7wen4ADSuDKFIpkWbeZvD27Zw7Tw"] },
    { id: 14, name: "Рубашка Oxford", brand: "FORMAL CO", category: "men", price: 5490, oldPrice: null, badge: "new", badgeText: "New", desc: "Классическая рубашка из ткани Oxford.", colors: ["#ffffff", "#87CEEB", "#f5f5dc"], sizes: ["S", "M", "L", "XL", "XXL"], reviews: [{name: "Владимир", stars: 4, text: "Хорошая ткань."}], image: "https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotBqjMbUFNh3wd0x3CcOE9PjSuDKFIpkWbeZvD27Zw7Tw", images: ["https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotBqjMbUFNh3wd0x3CcOE9PjSuDKFIpkWbeZvD27Zw7Tw"] },
    { id: 15, name: "Кроссовки Urban", brand: "STRIDE", category: "shoes", price: 8990, oldPrice: 12990, badge: "sale", badgeText: "-31%", desc: "Городские кроссовки в минималистичном дизайне.", colors: ["#808080", "#1a1a2e", "#ffffff"], sizes: ["36", "37", "38", "39", "40", "41", "42", "43"], reviews: [{name: "Кристина", stars: 5, text: "Очень лёгкие!"}], image: "https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotfWd7-K5vVj-GxZ76YLpkDTSuDKFIpkWbeZvD27Zw7Tw", images: ["https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotfWd7-K5vVj-GxZ76YLpkDTSuDKFIpkWbeZvD27Zw7Tw"] },
    { id: 16, name: "Ремень кожаный", brand: "VELORE", category: "accessories", price: 2990, oldPrice: null, badge: "hot", badgeText: "Хит", desc: "Классический ремень из натуральной кожи.", colors: ["#1a1a2e", "#8B4513", "#4a5d4e"], sizes: ["85", "90", "95", "100", "105"], reviews: [{name: "Григорий", stars: 5, text: "Красивая пряжка."}], image: "https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotkMAz8Bix9LAERPh002EWN2UQGk9StaSO2uPk4tWwj40", images: ["https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotkMAz8Bix9LAERPh002EWN2UQGk9StaSO2uPk4tWwj40"] },
    { id: 17, name: "Трикотажный кардиган", brand: "VELORE", category: "women", price: 7990, oldPrice: null, badge: "new", badgeText: "New", desc: "Уютный кардиган из мягкого трикотажа.", colors: ["#f5f5dc", "#1a1a2e", "#4a5d4e"], sizes: ["XS", "S", "M", "L", "XL"], reviews: [{name: "Юлия", stars: 5, text: "Очень мягкий!"}], image: "https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotxJZDQnLPzLAXu9wBKp5gtzSuDKFIpkWbeZvD27Zw7Tw", images: ["https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotxJZDQnLPzLAXu9wBKp5gtzSuDKFIpkWbeZvD27Zw7Tw"] },
    { id: 18, name: "Кожаные лоферы", brand: "STRIDE", category: "shoes", price: 9990, oldPrice: 13990, badge: "sale", badgeText: "-29%", desc: "Классические лоферы из натуральной кожи.", colors: ["#8B4513", "#1a1a2e", "#374151"], sizes: ["36", "37", "38", "39", "40", "41", "42"], reviews: [{name: "Алексей", stars: 5, text: "Очень удобные!"}], image: "https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotbfelKkuMCix80F5-uiQYYGUQGk9StaSO2uPk4tWwj40", images: ["https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotbfelKkuMCix80F5-uiQYYGUQGk9StaSO2uPk4tWwj40"] },
    { id: 19, name: "Шерстяной шарф", brand: "VELORE", category: "accessories", price: 3490, oldPrice: null, badge: "hot", badgeText: "Хит", desc: "Тёплый шарф из смесовой шерсти в клетку.", colors: ["#4a5d4e", "#7a3a4a", "#808080"], sizes: ["One Size"], reviews: [{name: "Виктория", stars: 5, text: "Качество на высоте!"}], image: "https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotIrdmoG8UFkL7pJYdwB5BRmUQGk9StaSO2uPk4tWwj40", images: ["https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotIrdmoG8UFkL7pJYdwB5BRmUQGk9StaSO2uPk4tWwj40"] },
    { id: 20, name: "Брюки чинос", brand: "FORMAL CO", category: "men", price: 6490, oldPrice: null, badge: "new", badgeText: "New", desc: "Универсальные чинос из хлопкового твила.", colors: ["#D2B48C", "#1a1a2e", "#374151"], sizes: ["44", "46", "48", "50", "52", "54"], reviews: [{name: "Павел", stars: 4, text: "Хорошая посадка."}], image: "https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotahsrKjLpiOP0zmyqtqJPwzSuDKFIpkWbeZvD27Zw7Tw", images: ["https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotahsrKjLpiOP0zmyqtqJPwzSuDKFIpkWbeZvD27Zw7Tw"] },
    { id: 21, name: "Платье-миди в горох", brand: "FEMME", category: "women", price: 8490, oldPrice: 11990, badge: "sale", badgeText: "-29%", desc: "Романтичное платье с принтом в горох.", colors: ["#1a1a2e", "#FFB6C1", "#f5f5dc"], sizes: ["XS", "S", "M", "L"], reviews: [{name: "Софья", stars: 5, text: "Сидит идеально!"}], image: "https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2Not9mDici4-lgphTlwvSSkvUzSuDKFIpkWbeZvD27Zw7Tw", images: ["https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2Not9mDici4-lgphTlwvSSkvUzSuDKFIpkWbeZvD27Zw7Tw"] },
    { id: 22, name: "Спортивная куртка", brand: "ACTIVE WEAR", category: "men", price: 10990, oldPrice: null, badge: "hot", badgeText: "Хит", desc: "Лёгкая ветровка с водоотталкивающим покрытием.", colors: ["#1a1a2e", "#4a5d4e", "#7a3a4a"], sizes: ["M", "L", "XL", "XXL"], reviews: [{name: "Игорь", stars: 5, text: "Не продувается!"}], image: "https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2Not_ZjLGy6U0Tx5vuQL4FsOJzSuDKFIpkWbeZvD27Zw7Tw", images: ["https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2Not_ZjLGy6U0Tx5vuQL4FsOJzSuDKFIpkWbeZvD27Zw7Tw"] },
    { id: 23, name: "Кожаный рюкзак", brand: "VELORE", category: "accessories", price: 12990, oldPrice: null, badge: "new", badgeText: "New", desc: "Стильный рюкзак из натуральной кожи.", colors: ["#8B4513", "#1a1a2e", "#374151"], sizes: ["One Size"], reviews: [{name: "Маргарита", stars: 5, text: "Качество кожи отличное!"}], image: "https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotfhUraz9eMRsdqstZmYq1OGUQGk9StaSO2uPk4tWwj40", images: ["https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotfhUraz9eMRsdqstZmYq1OGUQGk9StaSO2uPk4tWwj40"] },
    { id: 24, name: "Вязаный джемпер", brand: "LUXE KNIT", category: "women", price: 7490, oldPrice: 9990, badge: "sale", badgeText: "-25%", desc: "Уютный джемпер крупной вязки.", colors: ["#f5f5dc", "#4a5d4e", "#7a3a4a"], sizes: ["S", "M", "L", "XL"], reviews: [{name: "Елизавета", stars: 5, text: "Очень мягкий!"}], image: "https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotP7f2MbWAofUKx2ASDnRNczSuDKFIpkWbeZvD27Zw7Tw", images: ["https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotP7f2MbWAofUKx2ASDnRNczSuDKFIpkWbeZvD27Zw7Tw"] },
    { id: 25, name: "Кеды на платформе", brand: "STRIDE", category: "shoes", price: 8490, oldPrice: null, badge: "hot", badgeText: "Хит", desc: "Модные кеды на удобной платформе.", colors: ["#ffffff", "#1a1a2e", "#FFB6C1"], sizes: ["36", "37", "38", "39", "40", "41"], reviews: [{name: "Ксения", stars: 5, text: "Очень удобные!"}], image: "https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2Notg_B66trjy7rR3HbJTuEDJGUQGk9StaSO2uPk4tWwj40", images: ["https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2Notg_B66trjy7rR3HbJTuEDJGUQGk9StaSO2uPk4tWwj40"] },
    { id: 26, name: "Рубашка-поло", brand: "FORMAL CO", category: "men", price: 4990, oldPrice: null, badge: "new", badgeText: "New", desc: "Классическое поло из хлопкового пике.", colors: ["#ffffff", "#1a1a2e", "#374151"], sizes: ["S", "M", "L", "XL", "XXL"], reviews: [{name: "Антон", stars: 4, text: "Хорошее качество."}], image: "https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotCCI5QnuGGjXCRCwJKIyBgDSuDKFIpkWbeZvD27Zw7Tw", images: ["https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotCCI5QnuGGjXCRCwJKIyBgDSuDKFIpkWbeZvD27Zw7Tw"] },
    { id: 27, name: "Платок шёлковый", brand: "VELORE", category: "accessories", price: 2990, oldPrice: 3990, badge: "sale", badgeText: "-25%", desc: "Элегантный шёлковый платок с авторским принтом.", colors: ["#7a3a4a", "#964b00", "#1a1a2e"], sizes: ["One Size"], reviews: [{name: "Наталья", stars: 5, text: "Шёлк натуральный!"}], image: "https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotW5XYhxTV4n2J1KVV7evlIWUQGk9StaSO2uPk4tWwj40", images: ["https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotW5XYhxTV4n2J1KVV7evlIWUQGk9StaSO2uPk4tWwj40"] },
    { id: 28, name: "Юбка-миди плиссе", brand: "FEMME", category: "women", price: 6990, oldPrice: null, badge: "new", badgeText: "New", desc: "Лёгкая плиссированная юбка.", colors: ["#f5f5dc", "#1a1a2e", "#FFB6C1"], sizes: ["XS", "S", "M", "L"], reviews: [{name: "Алиса", stars: 5, text: "Очень лёгкая!"}], image: "https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotTBqy7yW6o3O2FANLEkI6MDSuDKFIpkWbeZvD27Zw7Tw", images: ["https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotTBqy7yW6o3O2FANLEkI6MDSuDKFIpkWbeZvD27Zw7Tw"] },
    { id: 29, name: "Ботинки челси", brand: "STRIDE", category: "shoes", price: 13990, oldPrice: 17990, badge: "sale", badgeText: "-22%", desc: "Классические челси из натуральной замши.", colors: ["#8B4513", "#1a1a2e", "#374151"], sizes: ["40", "41", "42", "43", "44", "45"], reviews: [{name: "Максим", stars: 5, text: "Качество замши отличное!"}], image: "https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotUmXx64XUJLGOmI9eZ7s5bWUQGk9StaSO2uPk4tWwj40", images: ["https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotUmXx64XUJLGOmI9eZ7s5bWUQGk9StaSO2uPk4tWwj40"] },
    { id: 30, name: "Сумка-кроссбоди", brand: "VELORE", category: "accessories", price: 7990, oldPrice: null, badge: "hot", badgeText: "Хит", desc: "Компактная сумка через плечо из эко-кожи.", colors: ["#1a1a2e", "#4a5d4e", "#7a3a4a"], sizes: ["One Size"], reviews: [{name: "Дарья", stars: 5, text: "Очень удобная!"}], image: "https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotibbbS8az9_tR5L3AeSJ0HGUQGk9StaSO2uPk4tWwj40", images: ["https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2NotibbbS8az9_tR5L3AeSJ0HGUQGk9StaSO2uPk4tWwj40"] },
    { id: 31, name: "Льняная рубашка", brand: "SUMMER LINE", category: "men", price: 5990, oldPrice: null, badge: "new", badgeText: "New", desc: "Лёгкая рубашка из 100% льна.", colors: ["#f5f5dc", "#87CEEB", "#1a1a2e"], sizes: ["S", "M", "L", "XL", "XXL"], reviews: [{name: "Денис", stars: 5, text: "Ткань дышит!"}], image: "https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2Not3W88JYNl5kdVnl4MLt25rDSuDKFIpkWbeZvD27Zw7Tw", images: ["https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2Not3W88JYNl5kdVnl4MLt25rDSuDKFIpkWbeZvD27Zw7Tw"] },
    { id: 32, name: "Бархатный клатч", brand: "VELORE", category: "accessories", price: 4490, oldPrice: 5990, badge: "sale", badgeText: "-25%", desc: "Элегантный клатч из мягкого бархата.", colors: ["#7a3a4a", "#1a1a2e", "#4a5d4e"], sizes: ["One Size"], reviews: [{name: "Арина", stars: 5, text: "Очень красивый!"}], image: "https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2Not1U8npAsbWi0x_flz882tiGUQGk9StaSO2uPk4tWwj40", images: ["https://i.oneme.ru/i?r=BTE2sh_eZW7g8kugOdIm2Not1U8npAsbWi0x_flz882tiGUQGk9StaSO2uPk4tWwj40"] }
];

// 📋 Информация для модальных окон
const infoData = {
    delivery: { 
        title: 'Доставка', 
        content: '<p><strong>Доставка по России:</strong> 1-7 дней. Бесплатно от 5000 ₽.</p><p>📦 Курьер, пункты выдачи, Почта России.</p>' 
    },
    returns: { 
        title: 'Возврат', 
        content: '<p><strong>30 дней</strong> на возврат товара.</p><p>Товар должен сохранить товарный вид.</p>' 
    },
    terms: { 
        title: 'Соглашение', 
        content: '<p>Используя сайт, вы соглашаетесь с условиями обработки данных.</p>' 
    }
};